### ISSUE TITLE
Warning when creating new package using ts-engine

### ISSUE THREAD

**Issue by James-Reed-cognito** [ts-engine/ts-engine#120] opened 2020-10-21 14:03 UTC
When creating a new package and installing dependencies, this message appears:

```warning @ts-engine/cli > rollup-plugin-babel@4.4.0: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-babel.```

It doesn't seem to have any immediate issue with how ts-engine works, but I figured it was worth raising an issue for to track. :)

**Comment by LeeCheneler** [comment] 2020-10-22 10:08
Duplicate of #114

**Closed by LeeCheneler** 2020-10-22 10:08 UTC
